name: Update Ingestion & Integration containers

on:
  push:
    branches:
      - N/A
#    tags:
#      - 0.0.30-SNAPSHOT
jobs:
  ingestion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker compose
        run: docker-compose build
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile Source Code
        run: sbt ingestion-application/assembly
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cdliotprototype/cdl-refit-ingestion
          tags: 0.0.30-SNAPSHOT
          path: applications/ingestion-application
      - name: Shut down docker-compose
        run: docker-compose down

  integrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker compose
        run: docker-compose build
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile Source Code
        run: sbt integrations-application/assembly
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cdliotprototype/cdl-refit-integrations
          tags: 0.0.30-SNAPSHOT
          path: applications/integrations-application
      - name: Shut down docker-compose
        run: docker-compose down
